apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-poc-ui-preact
data:
  Caddyfile: |
    :80
    root /srv
    gzip
    header / {
      #Strict-Transport-Security "max-age=31536000;"
      X-XSS-Protection "1; mode=block"
      X-Content-Type-Options "nosniff"
      X-Frame-Options "DENY"
    }
    mime .js text/javascript
    rewrite {
      to {path} {path}/ /
    }
    log stdout
    errors stdout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-poc-ui-preact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-poc-ui-preact
  template:
    metadata:
      labels:
        app: grpc-poc-ui-preact
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: grpc-poc-ui-preact
          image: alinflorin/grpc-poc-ui-preact:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 80
          volumeMounts:
            - name: grpc-poc-ui-preact
              mountPath: /etc/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: grpc-poc-ui-preact
          configMap:
            name: grpc-poc-ui-preact
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-poc-ui-preact
spec:
  selector:
    app: grpc-poc-ui-preact
  ports:
    - port: 80
      targetPort: 80
      name: http